// <auto-generated />
namespace ASP220211V3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class seed_elofizetes_tipusok : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed_elofizetes_tipusok));
        
        string IMigrationMetadata.Id
        {
            get { return "202202141509464_seed_elofizetes_tipusok"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
