// <auto-generated />
namespace ASP220211V3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SeedUgyfelekAndElofizetes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedUgyfelekAndElofizetes));
        
        string IMigrationMetadata.Id
        {
            get { return "202202141329173_SeedUgyfelekAndElofizetes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
